version: '2'

services:

  sonarqube:
    image: sonarqube:7.1
    ports:
      - '9000:9000'
      - '9092:9092'
    volumes:
      - ./data/sonarqube:/opt/sonarqube/data
    environment:
      - VIRTUAL_HOST=sonarqube
      - VIRTUAL_PORT=9000
    network_mode: bridge
